views: Save thumbnail file directly instead of using DesktopThumbnailFactory
endlessm/coding-chatbox pull request #70
Opened 2017-02-09 09:07 UTC by smspillaz

Using DesktopThumbnailFactory doesn't guarantee that the right-sized
thumbnail will be saved for our image. We always want a large
thumbnail and we always want it to be saved as a large thumbnail.

Doing so this way also allows us to keep track of the thumbnail path
as soon as the thumbnail is saved, which can then be passed on to
the CSS (instead of passing null in some cases).

https://phabricator.endlessm.com/T15359

2017-02-09 11:42 UTC, erikos requested changes
The patch does work - the attachment images are displayed properly. Cosimo might want to comment on the approach taken.

Some small comments on the patch from me.

2017-02-09 11:42 UTC, erikos commented on src/views.js
> -                thumbnailFactory.save_thumbnail(thumbnail, uri, mtime);
The comment above that code would need to be adjusted:

// A thumbnail does not currently exist. Ask libgnome-desktop to                                                                           
// create one (currently we do so synchronously) and then                                                                                  
// save the result.

2017-02-09 11:42 UTC, erikos commented on src/views.js
> +                    saveThumbnailError(targetThumbnailPath, uri, e);
s/targetThumbnailPath/thumbnailPath ?

2017-02-10 00:18 UTC, cosimoc requested changes
@smspillaz I am not a huge fan of doing things manually here, indeed.
A couple of points:
- it looks to me that this also does not guarantee that the right-sized thumbnail will be created, at least not in any way more than going through the thumbnail factory. The code first reads the GIO attribute for whether a thumbnail exists or not; that does not give us any information about the size of such thumbnail. If you want to make sure that the size is taken into account when looking it up, I think you can use `gnome_desktop_thumbnail_factory_lookup()` instead
- `gnome_desktop_thumbnail_factory_save_thumbnail()` is synchronous, so your code does not change the time the file gets on disk. If the real fix here is keeping track of the thumbnail path in this case, and passing it along, you can just call `gnome_desktop_thumbnail_path_for_uri()` or `gnome_desktop_thumbnail_factory_lookup()` after saving it, without the need to do it yourself

2017-02-10 00:18 UTC, cosimoc commented on src/views.js
> +    log('Saving of thumbnail ' + targetThumbnailPath + ' for ' +
Use `logError()`

2017-02-10 00:18 UTC, cosimoc commented on src/views.js
> +                } catch(e if e.matches(Gio.IOErrorEnum, Gio.IOErrorEnum.EXISTS)) {
Space before paren

2017-02-10 00:30 UTC, smspillaz commented
> gnome_desktop_thumbnail_factory_save_thumbnail() is synchronous, so your code does not change the time the file gets on disk. If the real fix here is keeping track of the thumbnail path in this case, and passing it along, you can just call gnome_desktop_thumbnail_path_for_uri() or gnome_desktop_thumbnail_factory_lookup() after saving it, without the need to do it yourself

Yeah thanks for the tip here - now that you mention it, it would have been this that was causing both problems. I did notice that the thumbnail path being passed out in the creation case was `null` though I had assumed that this might have been because things weren't committed to disk yet :)

Anyway, I'll give this approach a try, definitely sounds like the right one.

2017-02-10 00:47 UTC, smspillaz commented
Okay, tested the second approach and it seems to work great!

2017-02-10 00:56 UTC, cosimoc requested changes

2017-02-10 00:56 UTC, cosimoc commented on src/views.js
> +function saveThumbnailError(targetThumbnailPath, uri, e) {
This function is now unused.

2017-02-10 01:20 UTC, smspillaz commented on src/views.js
> +function saveThumbnailError(targetThumbnailPath, uri, e) {
It is too. I'm surprised that `save_thumbnail` doesn't take a `GError`.

2017-02-12 20:26 UTC, erikos commented
Looks good - comments addressed, and it works fine now for me. Thanks Sam for this one!

2017-02-12 20:27 UTC, merged